### ISSUE TITLE
Fix documentation for 2eorb keyword

### ISSUE THREAD

**Issue by jgonthier** [nwchemgit/nwchem#103]
The wiki documentation (https://github.com/nwchemgit/nwchem/wiki/TCE#2eorb----alternative-storage-of-two-electron-integrals) indicates that 2eorb can be used for all CC methods except those using an active space. I just tried to run CCSDT and it failed with:
```
tce_init: method incompatible with 2eorb
```
An old email thread from 2013 indicates that 2eorb doesn't work for non-CCSD methods (http://www.emsl.pnl.gov/docs/nwchem/nwchem-support/2013/09/0008.Re:_NWCHEM_How_to_include_CCSDT-LR_in_NW)

Am I doing something wrong, or is the 2eorb not supposed to work in this case? I'm using frozen core with CCSDT. I'm happy to edit the documentation myself if you let me know how to edit the Wiki.

**Comment by jeffhammond** [comment]
The documentation is incorrect.  It was correct in the past (up until version 6.3) but optimizations for CCSD-based models broke the use of `2eorb` for non-CCSD-based methods and since I am not aware of a resolution of that bug, the current solution is to prevent users from running a TCE job that will crash due to `hashv2: key not found`, possible after they've wasted a nontrivial amount of computer time.

As `2eorb` improves the efficiency of the four-index transformation, which is _usually_ an insignificant contributor to the wall time for models involving iteratively triples, you should just remove `2eorb`.

**Comment by jeffhammond** [comment]
You can submit a pull request against https://github.com/nwchemgit/nwchem-wiki to contribute to the documentation.

**Comment by jgonthier** [comment]
Sounds good, thank you. I have a new version ready for a PR, but before that, I guess the same restrictions apply to the 2emet keyword? I also tried it and obtained an error similar to that of 2eorb, if I'm not mistaken. I could update the docs for this keyword too.

**Comment by jgonthier** [comment]
My bad, the 2emet documentation already specifies that it has to be used with 2eorb.

**Comment by edoapra** [comment]
@jgonthier thanks for the wiki update
