### ISSUE TITLE
  When will the official new version of NWCHEM be released

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#119]
It has been around one and a half years since the official release of the last version of NWCHEM, i.e., NWCHEM6.8, which is the indispensable tools of atomic, molecular and perhaps mesoscopic research.
When will the official new version of NWCHEM, including the exscale edition, i.e., NWCHEM6.9, be released, which is anticipated to include many new functions?

**Comment by xiongyan21** [comment]
Is there still no the date of release announced?

**Comment by jeffhammond** [comment]
Is there a specific need for a release version?  I am using the latest git version all the time and every git hash constitutes a release of sorts, albeit without the rigorous validation the numbered releases get.

As for NWChemEx, that is a separate project.  Some developers contribute to both but it doesn't make sense to ask about NWChemEx releases here.

**Comment by xiongyan21** [comment]
Dear Dr. Jeff Hammond
   I wish to try the method developed in the article "Supersaturated Calcium Carbonate Solutions are Classical", but I am not sure whether it is included. Furthermore, I do not know where I can git the latest version.
Thanks.
Very Best Regards!

**Comment by hjjvandam** [comment]
Hi Xiong,

It seems to me that the paper uses ab-initio DFT MD for the dynamics, and TDDFT for the XANES spectra. Both methods have been available in NWChem for some time. The BLYP functional they used is certainly available. You would want to use the planewave capabilities for the periodic boundary conditions. The only things that will be different is that CP2K uses a different way to handle basis functions (Gaussian like atomic orbitals combined with planewave based integration) and the pseudo-potentials might be different. Otherwise NWChem 6.6 or 6.8 should be able to do these calculations.
However, if you want to use the latest version from the Github repository you can find it at: https://github.com/nwchemgit/nwchem

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov
Brookhaven National Laboratory

**Comment by jeffhammond** [comment]
@xiongyan21 You are literally on the website where you get the latest git version of NWChem.  Navigate back to https://github.com/nwchemgit/nwchem and look for the green button: 
<img width="1104" alt="Screen Shot 2019-06-06 at 8 32 30 AM" src="https://user-images.githubusercontent.com/406118/59045846-adadbf00-8835-11e9-961a-b409f3104e45.png">

**Comment by xiongyan21** [comment]
Thanks for the information and thanks for the clarification of the article to satisfy my specific needs, certainly increasing my use of quantum chemistry.
