### ISSUE TITLE
dft_he2+ test case is unstable if PEIGS is not used

### ISSUE THREAD

**Issue by mbanck** [nwchemgit/nwchem#184]
If I don't add `-DPARALLEL_DIAG` to `DEFINES`, I get the following numerical issues in the `dft_he2+` test case, which I did not observe before:

```
 Running tests/dft_he2+/dft_he2+

     cleaning scratch
     copying input and verified output files
     running nwchem (/<<PKGBUILDDIR>>/bin/LINUX64/nwchem)  with 1 processors

     verifying output ... failed
     Comparison of Output Files
@@ -1,4 +1,4 @@
 Effective nuclear repulsion energy (a.u.) 1.82
-Total DFT energy = -5.04038
+Total DFT energy = -3.34652
    Atoms             Coordinates:
          he      0.000      1.096      0.000
[...]
```

Is this a known issue?

**Comment by edoapra** [comment]
@mbanck No, this is not a known issue.
We need to investigate the root cause of it, since my recommendation for package builders is to deprecate Peigs in favor of Scalapack
Could you please point me to the recipe for reproducing this issue?

**Comment by edoapra** [comment]
@mbanck Commit https://github.com/edoapra/debichem-team/commit/4b21f68a4b6cdfafeaf71a52856c1c1dc3077c93 that replaces armci-mpi with the builtin mpi-ts (plus adoption of openblas) seems to work for me, once I use the libglobalarrays-dev package to link against nwchem 7.0.0

**Comment by jeffhammond** [comment]
That’s odd if ARMCI-MPI is causing this. I wonder if the underlying MPI library has RMA bugs.

**Comment by edoapra** [comment]
@jeffhammond I have not verified that the vanilla libglobalarrays-dev causes the breakage, since I am still waiting for @mbanck to give me the exact coordinates of the reproducer

**Comment by mbanck** [comment]
> @mbanck No, this is not a known issue.
> We need to investigate the root cause of it, since my recommendation for package builders is to deprecate Peigs in favor of Scalapack
> Could you please point me to the recipe for reproducing this issue?

Sorry, it seems I forgot to push the 7.0.0 changes to the debichem repo and upload it, I've done so now:

https://salsa.debian.org/debichem-team/nwchem/

Basically what I did is this: https://salsa.debian.org/debichem-team/nwchem/-/blob/master/debian/patches/16_disable_peigs.patch but there may be a better/actually correct way.

About your changes to GA - why did you set `--with-blas4=-lopenblas`? To the best of my knowledge, OpenBLAS is 8-Byte in Debian, contrary to refblas/reflapack.

**Comment by edoapra** [comment]
@mbanck thanks for your feedback. I believe the root cause of the problem you reported could be due to the handling of the integer size  for blas/lapack/scalapack.
The main problem is that if 4-byte is used for scalapack, same integer size should be used for blas/lapack. Therefore, if scalapack has 4-byte integer (I believe this is the case for Debian packages, correct me if I am wrong), then blas/lapack should use 4-byte integers.

Second point: libopenblas in Debian seem to be 4-byte, while libopenblas64 is 8-byte
https://salsa.debian.org/science-team/openblas/-/blob/master/debian/control

As far as your patch is concerned, this is going to have a big impact on performance, since it disable parallel linear algebra.
I am working at patches that allow to use Scalapack when Peigs is not available (or, in some cases, reverting back to sequential eigensolvers as your patch does). The patches are at the source code level, not makefile.
https://github.com/edoapra/debichem-team/blob/master/nwchem/debian/patches/17_pspw_scalapack.patch
https://github.com/edoapra/debichem-team/blob/master/nwchem/debian/patches/18_mcscf_scalapack.patch

My current Debian recipe seems to be working. 
https://github.com/edoapra/debichem-team/tree/master/nwchem
I will try to see if I am missing something from https://salsa.debian.org/debichem-team/nwchem/

**Comment by edoapra** [comment]
https://salsa.debian.org/debichem-team/nwchem/-/commit/475c7ecd1df5245247372099adb029d32b65c5d2
