### ISSUE TITLE
compile time issue with equivalence statement in util_pack.F

### ISSUE THREAD

**Issue by naromero77** [nwchemgit/nwchem#215]
Another issue with new flang, but this time I have no idea what to do about it. I am not very familiar with Fortran equivalence statements.

```
Compiling util_pack.F...
util_pack.F:14:26: error: Equivalence set cannot contain 'longw' that is numeric sequence type and 'shortw' that is not
        equivalence (longw,shortw)
```

**Comment by hjjvandam** [comment]
Hi Nick,

An equivalence statement associates two variables with the same address. Hence longw and shortw would occupy the same piece of memory when you have the


        equivalence (longw,shortw)

statement. As longw is an integer*8 and shortw is integer*2 shortw(4) the compiler should be able to handle this situation correctly (both datastructures should just be 8 bytes long). From this perspective I don’t understand the compiler’s error message talking about numerical sequences.

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by naromero77** [comment]
@hjjvandam Thanks for the explanation. Even though there is a workaround in NWChem. I will file a bugzilla issue for it.
https://bugs.llvm.org/show_bug.cgi?id=46334

**Comment by naromero77** [comment]
@edoapra @jeffhammond For those of you have a pedantic interest in Fortran, the use of equivalence here is technically not allowed. I know that Jeff has access to the LLVM bugzilla, but others do not. I copy and paste the relevant comments from that issue below.

The error is correct:
C8110 (R871) If an equivalence-object is default integer, default real, double precision real, default complex, default logical, or of numeric sequence type, all of the objects in the equivalence set shall be of these types and kinds.

**Comment by hjjvandam** [comment]
Hi Nick,

OK, so I don’t know what a numeric sequence is. I guess it is an array (or an array of numbers is a numeric sequence of some kind). The other thing is the reference to default data types. So

integer*8 longw(1)
integer*2 shortw(4)
equivalence(longw,shortw)

does not violate the criteria of C8110 (R871) (of course this might just mean that the behavior of this code is undefined according to the Fortran standard, which has its own issues).

Best wishes,

    Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory

**Comment by naromero77** [comment]
Now that I read the sentence from the Fortran ISO more carefully -- it does sound like it should be supported.

The textbook example that I have in my book for equivalence is:
```
      program main
      integer longw(2,2)
      integer shortw(4)
      equivalence (longw,shortw)

      write(6,*) ' size of  longw ', sizeof(longw)
      write(6,*) ' size of shortw ', sizeof(shortw)

      stop
      end
```

which does compile with `f18`.  Should you feel strongly that it needs to be supported in `f18`, I encourage you to comment on the LLVM bugzilla issue.

**Comment by hjjvandam** [comment]
Hi Nick,

Looking at it a bit closer the actual data types do not matter that much. The subroutine is merely testing the byte ordering in integer representations (big endian vs little endian). So the following code can always be used and I guess should be valid Fortran:


      subroutine util_pack_info(bytes_per_int, obigendian)

      implicit none

#include "mafdecls.fh"

      integer bytes_per_int

      logical obigendian

c

      integer*8 longw(1)

      integer*2 shortw(4)

      equivalence (longw,shortw)

c

      shortw(1) = 0

      longw(1) = 1

      obigendian = .not. (shortw(1) .eq. 1)

c

      bytes_per_int = ma_sizeof(mt_int, 1, mt_byte)

c

      end

To decide whether the architecture is big endian or little endian we need to establish whether the assignment “longw(1) = 1” sets shortw(4) to 1 (big endian) or whether it sets shortw(1) to 1 (little endian). Note that “integer” in NWChem is almost always promoted to integer*8 (I don’t know of any present day machine where we still use integer*4). However, according to the piece of the standard you quoted we are probably better off explicitly using integer*8 for longw, instead of the default data type. As the variables longw and shortw are local ones as well, it doesn’t hurt to be explicit about these data types.

Best wishes,

     Huub

-----------------------------------------------------------------------------------------------------
Hubertus van Dam, 631-344-6020, hvandam@bnl.gov<mailto:hvandam@bnl.gov>
Brookhaven National Laboratory
