### ISSUE TITLE
Bug when calculating gradient with XDM when using ChemShell

### ISSUE THREAD

**Issue by gh3orghiu** [nwchemgit/nwchem#27]
Hi there,

I've encountered a strange bug when using ChemShell's DL-FIND to optimise Butanol at the QM/MM level.

DL-FIND works by calculating the gradients at the QM level, then using this gradient information to perform the QM/MM optimisation step.

I am using NWChem 6.8 as my QM theory B3LYP/6-31G* with XDM for dispersion and for MM theory a generated Amber Forcefield. 

I put forward a few scenarios to help the debugging process:

1) 'chemsh_xdm/1_cycle' Using ChemShell to launch NWChem (as an executable) for ONE optimisation cycle.
As you can see from the nwchem  output, the gradient has been calculated successfully

2) 'chemsh_xdm/2_cycle' Using ChemShell to launch NWChem (as an executable) for TWO optimisation cycles.
This time, ChemShell will automatically generate a restart nwchem input and execute this restart. 
As you can see from the nwchem output, the gradient is calculated as NaN – which then causes the DL-FIND optimisation procedure to crash.

3) 'chemsh_xdm/w_out_xdm' Using ChemShell to launch NWChem (as an executable) without XDM. The ChemShell DL-FIND optimisation completes successfully.

4) 'nwchem_only_xdm/' When I take the NWChem input generated by ChemShell in 1), and run it through NWChem standalone – The calculation completes successfully.

5) '*not included*' When I take the NWChem input generated by ChemShell in 2), and run through NWChem standalone – The calculation crashes (which is expected since it is a restart input)

[xdm_bug.zip](https://github.com/nwchemgit/nwchem/files/1837260/xdm_bug.zip)

Please take a look at the following zip file, which contains a tar file with all the directories, log files and inputs. 

Thanks,
Alex

**Comment by edoapra** [comment]
@gh3orghiu Alex, your calculations hit a bug when using xdm with the restart option.
I have checked in a fix in the master and hotfix/release-6-8 branches.
As a workaround when using NWChem 6.8, you can add the following line just before the task line
```
set dft:xdmsave f
```
By the way, the way ChemShell is using the NWChem   [restart](https://github.com/nwchemgit/nwchem/wiki/Start_Restart) is rather odd.
Cheers, Edo

**Comment by edoapra** [comment]
No further feedback has been received

**Comment by gh3orghiu** [comment]
Hi @edoapra , any chance to re-open this query? 

Sorry I took a while to respond but I noticed that your fix did work, but I've now encountered a new bug that only effects diffuse basis sets.

When using 6-31G and 6-31G*(*) the gradients are calculated fine
When using 6-31+G or any other combination that include diffuse option, the gradient is once again calculated as NaN, disrupting the ChemShell optimisation procedure.

**Comment by gh3orghiu** [comment]
Here is the data with my supporting evidence, a zip file containing a tar file with the directories appropriately labelled. 

[xdm_diffuse_bug.zip](https://github.com/nwchemgit/nwchem/files/1852054/xdm_diffuse_bug.zip)

**Comment by edoapra** [comment]
@gh3orghiu I could not spot any Nan number in the output files after extracting the tarball you provided.
Could you please provide more detailed instructions?
Cheers, Edo

**Comment by gh3orghiu** [comment]
Dear @edoapra ,

Sorry for wasting your time with the above files. However, it appears that what I've sent you uses the B3LYP functional.

The functional that I am intending to use is a combination of pw86 and pbe, which I call with the following command in the dft block.
'xc xperdew86 1.0 cpbe96 1.0'

Please see the revised tarball, where the folder 6-31plplgstst contains NaN in the NWChem output.
(The other basis sets appear to work fine.. )

[xdm_diffuse_bug_pw86pbe.zip](https://github.com/nwchemgit/nwchem/files/1852970/xdm_diffuse_bug_pw86pbe.zip)

**Comment by gh3orghiu** [comment]
@edoapra Actually upon rerunning the 6-31++G** calculation, it appears to calculate the gradient correctly ...strange. This is however only for butanol, which is just simply a test case.

I first noticed the bug when studying DNA fragments for example, take a look here we have three types of basis sets tested with the pw86 & pbe functional:

1) 6-31G (works)
2) 6-31G* (works)
3) 6-31+G (fails)
4) 6-31++G** (desired basis) (fails)

[dna_pw86pbe_xdm_bug.zip](https://github.com/nwchemgit/nwchem/files/1853025/dna_pw86pbe_xdm_bug.zip)

I wanted to avoid using my specific inputs since they are a bit more confusing than Butanol but here they are.

**Comment by edoapra** [comment]
@gh3orghiu I have spotted a problematic spot in the routine for PW86 exchange.
It is a bug
Later,  Edo

**Comment by edoapra** [comment]
@gh3orghiu I have just commited a fix to the hotfix/release-6-8 tree
https://github.com/nwchemgit/nwchem/commit/1ec334342535268c233ee6802570775f10bf8cd9
Let me know if you need help in compiling the hotfix/release-6-8 branch

**Comment by gh3orghiu** [comment]
@edoapra thanks for the quick fix! I'm in process of recompiling the latest release of nwchem and will post back results when complete.

Thanks again!

**Comment by gh3orghiu** [comment]
@edoapra I've been experiencing an issue trying to compile this newer version of NWChem. 

It gets to the last step of compilation then error (see attached make.log):
' ifort: error #10236: File not found:  '/opt/intel/mpi-rt/2017.0.0/intel64/lib/release_mt'
ifort: error #10236: File not found:  '/opt/intel/mpi-rt/2017.0.0/intel64/lib' '

Even though I have defined the 'release_mt' to a valid directory in my compile script.

Any idea what I am missing here?

Thanks
Alex
[nwchem-6.8-compile-grace.zip](https://github.com/nwchemgit/nwchem/files/1856684/nwchem-6.8-compile-grace.zip)

**Comment by edoapra** [comment]
Alex

The ifort error you report might be due to an incorrect installation of ifort, since in your log file you can create object files but the final linking step fails ... did you try to compile a very simple fortran code to verify that ifort can produce an executable?

Anyhow, I have spotted a few issues in your compilation environment (but I am doubtful that they will solve the linking problem, but you might try). Please try the following changes (they are need anyway to get the right Blas and Scalapack libraries)

export BLASOPT="-L${MKLROOT}  -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lm -ldl"

export BLAS_SIZE=4

export SCALAPACK="-L${MKLROOT} -lmkl_scalapack_lp64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core  -lmkl_blacs_intelmpi_lp64   -ldl"

export SCALAPACK_SIZE=4


After setting the new environment, please do the following

cd $NWCHEM_TOP/src/tools

make clean

rm -rf build install

make FC=ifort

cd ../64to32

make clean;make FC=ifort

cd ..

make FC=ifort link



On 3/28/18 8:46 AM, gh3orghiu wrote:

@edoapra<https://github.com/edoapra> I've been experiencing an issue trying to compile this newer version of NWChem.

It gets to the last step of compilation then error (see attached make.log):
' ifort: error #10236: File not found: '/opt/intel/mpi-rt/2017.0.0/intel64/lib/release_mt'
ifort: error #10236: File not found: '/opt/intel/mpi-rt/2017.0.0/intel64/lib' '

Even though I have defined the 'release_mt' to a valid directory in my compile script.

Any idea what I am missing here?

Thanks
Alex
nwchem-6.8-compile-grace.zip<https://github.com/nwchemgit/nwchem/files/1856684/nwchem-6.8-compile-grace.zip>

**Comment by edoapra** [comment]
@gh3orghiu Please update your tree. I have just committed a fix
https://github.com/nwchemgit/nwchem/commit/a0e92a78a31a98c5b52a22e5c39b1430a3f57881

**Comment by gh3orghiu** [comment]
Hi @edoapra ,

Sorry for the delay, university was closed for holidays.
I will try again today with the above corrections.

Thanks, Alex
