### ISSUE TITLE
Undefined symbols dormtr referenced by dsyevd

### ISSUE THREAD

**Issue by jeffhammond** [nwchemgit/nwchem#276]
I am using internal BLAS, and it seems LAPACK is missing a dependency in BLAS.

```
/Applications/Xcode.app/Contents/Developer/usr/bin/make nwchem.o stubs.o
gfortran-10 -cpp  -fdefault-integer-8 -fno-aggressive-loop-optimizations -Warray-bounds -fno-tree-dominator-opts  -std=legacy -fopenmp -g -fno-aggressive-loop-optimizations -fno-tree-dominator-opts   -I.  -I/Users/jrhammon/Work/NWCHEM/github/src/include -I/Users/jrhammon/Work/NWCHEM/github/src/tools/install/include -DMACX -DEXT_INT -DGFORTRAN -DGCC4 -DGCC46 -DUSE_OPENMP -DUSE_OPENMP_TASKS -DPARALLEL_DIAG -DUSE_F90_ALLOCATABLE -DCOMPILATION_DATE="'`date +%a_%b_%d_%H:%M:%S_%Y`'" -DCOMPILATION_DIR="'/Users/jrhammon/Work/NWCHEM/github'" -DNWCHEM_BRANCH="'7.0.0'"  -c -o nwchem.o nwchem.F
gfortran-10 -cpp  -fdefault-integer-8 -fno-aggressive-loop-optimizations -Warray-bounds -fno-tree-dominator-opts  -std=legacy -fopenmp -g -fno-aggressive-loop-optimizations -fno-tree-dominator-opts   -I.  -I/Users/jrhammon/Work/NWCHEM/github/src/include -I/Users/jrhammon/Work/NWCHEM/github/src/tools/install/include -DMACX -DEXT_INT -DGFORTRAN -DGCC4 -DGCC46 -DUSE_OPENMP -DUSE_OPENMP_TASKS -DPARALLEL_DIAG -DUSE_F90_ALLOCATABLE -DCOMPILATION_DATE="'`date +%a_%b_%d_%H:%M:%S_%Y`'" -DCOMPILATION_DIR="'/Users/jrhammon/Work/NWCHEM/github'" -DNWCHEM_BRANCH="'7.0.0'"  -c -o stubs.o stubs.F
gfortran-10 -fopenmp -L/Users/jrhammon/Work/NWCHEM/github/lib/MACX64 -L/Users/jrhammon/Work/NWCHEM/github/src/tools/install/lib  -Wl,-flat_namespace -o /Users/jrhammon/Work/NWCHEM/github/bin/MACX64/nwchem nwchem.o stubs.o -lnwctask -lccsd -lmcscf -lmp2 -lmoints -lstepper -ldriver -loptim -lnwdft -lgradients -lcphf -lesp -lddscf -lguess -lhessian -lvib -lnwcutil -lrimp2 -lproperty -lsolvation -lnwints -ldplot -lvscf -letrans -ltce -lbq -lcons -ldimqm -lnwcutil -lga -larmci -lpeigs -lperfm -lcons -lbq -lnwcutil -lnwclapack  -lnwcblas    -lnwclapack  -lnwcblas  -L/Users/jrhammon/Work/NWCHEM/github/external-armci/lib -larmci -L/usr/local/lib -Wl,-flat_namespace -Wl,-commons,use_dylibs -L/usr/local/lib -Wl,-rpath -Wl,/usr/local/lib -L/usr/local/opt/libevent/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lpthread  -L/Users/jrhammon/Work/NWCHEM/github/external-armci/lib -larmci  -lpthread   
Undefined symbols for architecture x86_64:
  "_dormtr_", referenced from:
      _dsyevd_ in libnwclapack.a(dsyevd.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [all] Error 1
```

It seems there have been some changes lately that might have triggered this:

```
commit 81e08d45a81fa7e01e586c80ef8a77be577b8b77
Author: edoapra <edoardo.apra@gmail.com>
Date:   Thu Nov 26 15:45:11 2020 -0800

    dsyevd replaced dsyevd

commit d288a055b7a0f48c8877d4d58ee1bccbfeaac194
Author: edoapra <edoardo.apra@gmail.com>
Date:   Thu Nov 26 15:44:32 2020 -0800

    dsyevd

commit 16b22d1f525c29393d9398f636f894464fb059ce
Author: edoapra <edoardo.apra@gmail.com>
Date:   Thu Nov 26 10:47:52 2020 -0800

    use fast_diag instead of dsyev to avoid 64to32 breakage
```

I cannot find the implementation in git...
```
jrhammon-mac02:src jrhammon$ git grep -i dormtr
lapack/double/dsyevd.f:      EXTERNAL           DLACPY, DLASCL, DORMTR, DSCAL, DSTEDC, DSTERF,
lapack/double/dsyevd.f:*     tridiagonal matrix, then call DORMTR to multiply it by the
lapack/double/dsyevd.f:         CALL DORMTR( 'L', UPLO, 'N', N, N, A, LDA, WORK( INDTAU ),
```

```
export NWCHEM_TARGET=MACX64
export NWCHEM_MODULES=qm
#export NWCHEM_MODULES=smallqm
export NWCHEM_TOP=/Users/jrhammon/Work/NWCHEM/github

export USE_MPI=y
export ARMCI_NETWORK=ARMCI
export COMEX_NETWORK=ARMCI
export EXTERNAL_ARMCI_PATH=$NWCHEM_TOP/external-armci

#MPI_DIR=`which mpicc | sed "s/\/bin\/mpicc//g"`
MPI_DIR=/usr/local
export MPI_LIB="${MPI_DIR}/lib"
export MPI_INCLUDE="${MPI_DIR}/include"
#MPI_LIBS="-lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi"
OMPI_LIBS="-L/usr/local/opt/libevent/lib"
#gfortran -I/usr/local/Cellar/open-mpi/4.0.2/include -Wl,-flat_namespace -Wl,-commons,use_dylibs -I/usr/local/Cellar/open-mpi/4.0.2/lib -L/usr/local/opt/libevent/lib -L/usr/local/Cellar/open-mpi/4.0.2/lib -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi
export LIBMPI="-Wl,-flat_namespace -Wl,-commons,use_dylibs -L${MPI_DIR}/lib -Wl,-rpath -Wl,${MPI_DIR}/lib ${OMPI_LIBS} ${MPI_LIBS} -lpthread"
#export LIBMPI="-Wl,-flat_namespace -Wl,-commons,use_dylibs -L/usr/local/opt/libevent/lib -L${MPI_DIR}/lib -lmpi"
#export NO_MPIF=T

export CC=gcc-10
export FC=gfortran-10
export F77=gfortran-10

#export BLASOPT="-framework Accelerate -fopenmp"
#export BLAS_LIB=$BLASOPT
#export LAPACK_LIB=$BLASOPT
export USE_INTERNALBLAS=y

#export NO_MPIF=T

export MPICC=${MPI_DIR}/bin/mpicc
export MPICXX=${MPI_DIR}/bin/mpicxx
export MPIFC=${MPI_DIR}/bin/mpifort
export MPIF77=${MPI_DIR}/bin/mpifort
```

**Comment by edoapra** [comment]
@jeffhammond thanks for catching this

**Comment by edoapra** [comment]
Not quite sure if it makes sense to keep maintaining `USE_INTERNALBLAS`.
I am inclined to make `BUILD_OPENBLAS=y` the default. The increase for time to compile is negligible compared to the overall NWChem compile time. 
Any thoughts?

**Comment by jeffhammond** [comment]
I've had problems with OpenBLAS in the past, but I suppose I can just roll my own Netlib install when necessary.  OpenBLAS is a good default for most users.

My ultimate hope is that we can make all the 32/64 workarounds unnecessary and then it will be a lot easier to use the right external BLAS.  I dislike the source code translation trick, since that is very bad on version control.  I just need to make time to implement something.  Maybe I will do it over the winter holiday.

**Comment by edoapra** [comment]
> My ultimate hope is that we can make all the 32/64 workarounds unnecessary and then it will be a lot easier to use the right external BLAS. I dislike the source code translation trick, since that is very bad on version control. I just need to make time to implement something. Maybe I will do it over the winter holiday.

That's the whole point of using together the following setting ... 64_to_32 is no longer needed. I thought I my message was clear in the other related issue
```
BUILD_OPENBLAS=1
BUILD_SCALAPACK=1
BLAS_SIZE=8
SCALAPACK_SIZE=8
```
OpenBLAS seems always more stable than any other BLAS implementation I have tried. All my Travis CI and Gitlab CI use them by default

**Comment by ebylaska** [comment]
In principle this seems like a reasonable thing to do, and I like that nwchem can now automatically install openblas.   However, I can see two drawbacks.

 
Your potentially requiring the machine you’re compiling on to be connected to the internet, and there are several commercial and security computing environments where this is not the case (or even a woolly “unibomber” living in cabin with limited internet access).  As a result these users have to figure out how to download the external libraries and install them in the proper way.   Of course this is already happening with GA and (now) MPI at the moment, but one could always in the future just fold GA directly into the nwchem tree.  With a truly separate development such as openblas you’ll be setting a precedent to using a bunch of external libraries which inevitably won’t work on somebody’s system (making the compilation like some applied math code from a ascr lab (or some graduate student’s C++ code) that never seems to work – thankfully they have not yet decided they’re javascript experts and masters of conflated DOMs).  
It’s nice that there’s an option to just use some straightforward fortran code for BLAS/LAPACK rather than having to depend on some external dependency.  The USE_INTERNALBLAS code doesn’t really change, and when it does it’s a simple port, so maintaining this less used option seems reasonable to me.
 

Of course, making BUILD_OPENBLAS=y the default doesn’t mean getting rid of the USE_INTERNALBLAS.  While we’ll be less likely find future bugs in USE_INTERNALBLAS  as quickly as we do now, it doesn’t seem like this will occur very often.

**Comment by edoapra** [comment]
How is the *unabomber* going to get that NWChem tarball? I am assuming that, somewhere down the chain, a tarball is downloaded from the internet, isn't it? Then the tarball is somehow transferred to the computer where NWChem is going to be installed
If you agree that this is a plausibile scenario, what about providing a `download_extrabits.sh` script that download all the extra component that NWChem might use:
* Global Arrays
* OpenBLAS
* ScaLapack
* Simint

The log cabin dweller will need to copy the NWChem tarball plus the extra tarballs to the  off-the-network computer. We would not need to distribute the tar balls ourselves, just to provide the download script, instead.

**Comment by jeffhammond** [comment]
@edoapra Yeah, sorry, I know that solves the problem when OpenBLAS works, but if e.g. Apple M1 doesn't support OpenBLAS yet, then Apple's Accelerate framework is going to be required, and Accelerate only supports the LP64 ABI.  Of course, right now, Apple M1 doesn't have a Fortran compiler, so NWChem is DOA anyways, but it's an example of a platform where OpenBLAS might not "just work".

**Comment by ebylaska** [comment]
One more thing.  By using openblas I’m think you’ll have to always do a 64to32 conversion.

 

From: "Bylaska, Eric J" <bylaska@gmail.com>
Date: Monday, November 30, 2020 at 2:00 PM
To: nwchemgit/nwchem <reply@reply.github.com>
Subject: Re: [nwchemgit/nwchem] Undefined symbols dormtr referenced by dsyevd (#276)

 

In principle this seems like a reasonable thing to do, and I like that nwchem can now automatically install openblas.   However, I can see two drawbacks.

 
Your potentially requiring the machine you’re compiling on to be connected to the internet, and there are several commercial and security computing environments where this is not the case (or even a woolly “unibomber” living in cabin with limited internet access).  As a result these users have to figure out how to download the external libraries and install them in the proper way.   Of course this is already happening with GA and (now) MPI at the moment, but one could always in the future just fold GA directly into the nwchem tree.  With a truly separate development such as openblas you’ll be setting a precedent to using a bunch of external libraries which inevitably won’t work on somebody’s system (making the compilation like some applied math code from a ascr lab (or some graduate student’s C++ code) that never seems to work – thankfully they have not yet decided they’re javascript experts and masters of conflated DOMs).  
It’s nice that there’s an option to just use some straightforward fortran code for BLAS/LAPACK rather than having to depend on some external dependency.  The USE_INTERNALBLAS code doesn’t really change, and when it does it’s a simple port, so maintaining this less used option seems reasonable to me.
 

Of course, making BUILD_OPENBLAS=y the default doesn’t mean getting rid of the USE_INTERNALBLAS.  While we’ll be less likely find future bugs in USE_INTERNALBLAS  as quickly as we do now, it doesn’t seem like this will occur very often.

**Comment by edoapra** [comment]
> One more thing.  By using openblas I’m think you’ll have to always do a 64to32 conversion. 

Only when `BLAS_SIZE=4` you need the 64to32 conversion.
OpenBLAS has been supporting 64bit integers for a while. Using `BLAS_SIZE=8` and `BUILD_OPENBLAS=1` builds OpenBLAS with 64-bit ints and passes the same information to the Global Arrays configuration

**Comment by ebylaska** [comment]
Hmm….I just did a new compilation openblas and dsyev failed.  Do I manually need to set BLAS_SIZE?

**Comment by edoapra** [comment]
> @edoapra Yeah, sorry, I know that solves the problem when OpenBLAS works, but if e.g. Apple M1 doesn't support OpenBLAS yet, then Apple's Accelerate framework is going to be required, and Accelerate only supports the LP64 ABI (AFAIK). Of course, right now, Apple M1 doesn't have a Fortran compiler, so NWChem is DOA anyways, but it's an example of a platform where OpenBLAS might not "just work".

Right, it is an example but not a good one since you don't have a native software stack for scientific computing on the M1 chip yet (I am guessing you can use the Rosetta emulation to use x86 tools, isn't it)

**Comment by edoapra** [comment]
> Hmm….I just did a new compilation openblas and dsyev failed.  Do I manually need to set BLAS_SIZE? 

Are you building OpenBLAS inside NWChem with `BUILD_OPENBLAS`?
Are you using pre-installed OpenBLAS packages?
If you are using `BUILD_OPENBLAS=1` you  need to set `BLAS_SIZE=8` (it might be a good idea to change the default, isn't it?)

**Comment by ebylaska** [comment]
I just rebuilt on my macbook pro using the BUILD_OPENBLAS=y option that downloads and builds it libext…However, I didn’t remember to set BLAS_SIZE=8 which I typically have set on other machines.  I agree that changing the default to BLAS_SIZE=8 is probably a good idea at this point when using BUILD_OPENBLAS. When using openblas in the past I just used BLASOPT environment variable.
