### ISSUE TITLE
Please have an option to use external libga.so

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#28]
You are trying to download it, while I have it pre-installed.
Could you please have an option to use preinstalled ga?

**Comment by jeffhammond** [comment]
The external build of GA may not support PeIGS or compatible Fortran compiler flags that are required by NWChem.  There is a reason that NWChem builds GA itself.

I know how to implement this, but I suspect that it will only create problems, rather than solve them.  Building GA as part of NWChem is not the bottleneck in generating binaries.

**Comment by edoapra** [comment]
Need information from GA that is not present at this time.
See for example
https://github.com/GlobalArrays/ga/issues/99

**Comment by edoapra** [comment]
Commits
https://github.com/nwchemgit/nwchem/commit/f2c8907f59c23568db13a87d3f2b4307272bf68d 
https://github.com/nwchemgit/nwchem/commit/3e0f59d3627fa79c27fae3a249afd85e356d271f 
and https://github.com/nwchemgit/nwchem/commit/635ace19e5ac85510fb050ca591ecaeef74b3a47 allow use of external GAs  in NWChem.
The whole thing is triggered by the setting of the env. variable EXTERNAL_GA_PATH (that contains the root directory of external GA installation).
GA version 5.6.5 (or more recent versions) is required.
