### ISSUE TITLE
It seems there is no use of of the vectors input in QA test DUCC_Be

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#310]
It seems there is no use of of the vectors input in QA test DUCC_Be, i.e., vectors input Be-cc-pVTZ.movecs in scf group.
Why?

The log files are attached.

Very Best Regards!

[ducc_be.log](https://github.com/nwchemgit/nwchem/files/5847035/ducc_be.log)
[ducc_be1.log](https://github.com/nwchemgit/nwchem/files/5847039/ducc_be1.log)

**Comment by xiongyan21** [comment]
I used the geometry of water in QA test tce_ccsd_t_h2o for quantum rotation algorithm input, and it was OK.
The log files are attached.

Very Best Regards!
[tce_quantum_rotations2.log](https://github.com/nwchemgit/nwchem/files/5847676/tce_quantum_rotations2.log)

**Comment by xiongyan21** [comment]
The first two excitation roots of  water, also using that geometry, with and without quantum computing algorithm are OK, getting the same results, but I don't know whether they are correct.

Very Best Regards!

[h2o-2.log](https://github.com/nwchemgit/nwchem/files/5847774/h2o-2.log)
[h2o-1.log](https://github.com/nwchemgit/nwchem/files/5847784/h2o-1.log)

**Comment by npbauman** [comment]
Concerning the Be example, If you do a normal SCF calculation, you will see that it does not have to do any iterations to converge anything. That means if you perform a 'noscf' calculation the integrals will be essentially the same as if you did perform an SCF calculation. The QA test reads in integrals obtained from an SCF calculation. The reason that the integrals are read in for this test is so that when the list of integrals is printed out, later on, they are consistent in phase with the expected quantities since the Be atom has degeneracies that would otherwise cause issues.

It does not sound like there is an issue with the rotations routine according to your comment.

For your last H2O example, you spelled "integrals" wrong in the 'set tce:print_integrals' keyword. As a result, the two examples will run CCSD normally and compute the first two excited states. Even if the keyword was spelled correctly, the only thing that it does is print out the 1- and 2-electron integrals from the Hamiltonian. There is no quantum computation done and the resulting CCSD/EOMCCSD would be no different than if you did not have the keyword.

**Comment by xiongyan21** [comment]
Dear Dr. Bauman
By the imitation of the input of PES of water,  the calculation is OK, and I will study the input.
Very Best Regards!

[h2o-2.log](https://github.com/nwchemgit/nwchem/files/5879887/h2o-2.log)

**Comment by xiongyan21** [comment]
Dear Dr. Bauman
The one without quantum calculation gets a little different result.
[h2o-3.log](https://github.com/nwchemgit/nwchem/files/6134059/h2o-3.log)


Very Best Regards!

**Comment by npbauman** [comment]
@xiongyan21 
The documentation describes what the problem is:
"If the number of electrons and orbitals do not correspond to the total numbers of electrons and orbitals, then the calculation will perform a corresponding frozen core/frozen virtual CC/EOMCC calculation. This is to ensure that leading CC/EOMCC excitations do not correspond to orbitals outside of the printed integrals."

From your outputs, you can see that in one calculation you are freezing 17 virtual orbitals, while the other does not freeze any.

**Comment by xiongyan21** [comment]
Dear Dr. Bauman
 The following test with and without freezing seem to get the same ccsd total energy.
Very Best Regatds!
[be_6-31g.log](https://github.com/nwchemgit/nwchem/files/6136052/be_6-31g.log)
[be_6-31g_fci.log](https://github.com/nwchemgit/nwchem/files/6136053/be_6-31g_fci.log)

**Comment by npbauman** [comment]
The number of orbitals chosen by the active space is the number of total orbitals, meaning that the calculation will not freeze any orbitals. You can see that in the list of parameters printed at the beginning of the CC calculation in both outputs. These two outputs are the same calculation in the end.
