### ISSUE TITLE
Deleted

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#314]

**Comment by xiongyan21** [comment]
The replacement of 6-31G with aug-ccpv-dz of the QA test cytosine  gets a stuck, and the employment of 6-31+G** still gets very high exciatation energies.
[cytosine.log](https://github.com/nwchemgit/nwchem/files/5971345/cytosine.log)

Very Best Regards!

**Comment by xiongyan21** [comment]
Is it only suitable for cow-level states?

Very Best Regards!

**Comment by xiongyan21** [comment]
I am trying using second order FCI and quantum computing to calculate the excitation energies of a small radical.

Very Best Regards!

**Comment by npbauman** [comment]
Since I do not have inputs/outputs to examine, I can venture to guess that the problem with the calculations is a combination of the following things:

1. From the manual: "If the number of electrons and orbitals do not correspond to the total numbers of electrons and orbitals, then the calculation will perform a corresponding frozen core/frozen virtual CC/EOMCC calculation. This is to ensure that leading CC/EOMCC excitations do not correspond to orbitals outside of the printed integrals." If you are printing the standard Hamiltonian, you are likely freezing several orbitals and not doing an equivalent calculation to compare with the QA test.

2. EOMCCSD and CR-EOMCCSD(T) are different methods, so you can expect different solutions for excitation energies. 

The first issue is likely the problem that you are encountering.
