### ISSUE TITLE
Intel MKL ERROR: Parameter 5 was incorrect on entry to DSYMV .

### ISSUE THREAD

**Issue by miroi** [nwchemgit/nwchem#318]
Hello,

with the fresh OpenMPI-Intel-MKL  compiled nwchem-master I got error "Intel MKL ERROR: Parameter 5 was incorrect on entry to DSYMV", while the 7.0.2 release continue calculation without this bug.

Files:
[HD.zip](https://github.com/nwchemgit/nwchem/files/5898600/HD.zip)

**Comment by edoapra** [comment]
@miroi  
This issue is very hard to handle without knowing how you compiled NWChem.
This error is quite likely to be caused by an incorrect setting of the MKL libraries
https://nwchemgit.github.io/Compiling-NWChem.html#how-to-deal-with-integer-size-of-linear-algebra-libraries
However, it would be extremely useful if you could report the environment variable you used for the NWChem compilation and a detailed description of the make commands you have executed.
Another important piece information is contained in the file `$NWCHEM_TOP/src/tools/build/config.log` ... could you post this file, too?

**Comment by mjklemm** [comment]
I have seen this error before when I linked with the LP64 version of MKL and should have used the ILP64. In the LP64 version, integer arguments are 32bits while for the ILP64 version the integer size is 64bit.

If you're using 64bit for NWChem, you need to change the MKL library to mkl_intel_ilp64 from mkl_intel_lp64

**Comment by jeffhammond** [comment]
-mkl -i8 should do the right thing. Not sure if that’s used.

**Comment by miroi** [comment]
Dear Jeff ( @jeffhammond ),
so mean simple prescription for blas/lapack libraries, like
~~~
export BLASOPT="-mkl -i8"
 export LAPACK_LIB="-mkl -i8"
export USE_64TO32="n"
export BLAS_SIZE=8
export LAPACK_SIZE=8
export LARGE_FILES=1
.
.
~~~
And in the case of integer*8: do the OpenMPI suite  has to be compiled with -i8 ?

**Comment by jeffhammond** [comment]
> And in the case of integer*8: does the OpenMPI suite have to be compiled with -i8 ?

You should never do that.

First it has no effect on NWChem because that flag only affects the Fortran bindings, and the only place NWChem uses the Fortran bindings is in NWPW, which has it's own wrappers that deal with 4/8 issues.  The rest of NWChem uses the MPI C bindings via Global Arrays.

Second, `-i8` is a lie from the standpoint of MPI, because implementations will not actually deal with integer values that exceed `INT_MAX`.  Maybe once MPI-4 large count support is implemented that will change, but even then, one should not use `-i8`, because there is a better way to set large arguments.

**Comment by miroi** [comment]
I did not delete previous compiler object files, afer proper cleaning of all files (**git clean -d -f -x .**) all is fine.
