### ISSUE TITLE
Can quantum calculation accurately estimate activation energies?

### ISSUE THREAD

**Issue by xiongyan21** [nwchemgit/nwchem#321]
Can quantum calculation accurately estimate activation energies?

Very Best Regards!

**Comment by xiongyan21** [comment]
I use DUCC to calculate an heterocyclic. a reactant of a ring opening reaction,  but et the following mistake
... 
For more information see the NWChem manual at https://github.com/nwchemgit/nwchem/wiki


 For further details see manual section:                                                                                                                                                                                                                                                                
 prt2                 104 
The geometry here is from mp2 by GAMESS. I will use NWCHEM to optimize it and retry.

Very Best Regards!

**Comment by xiongyan21** [comment]
It seems the best way to apply quantum computation is to follow the accompanying tests.

Very Best Regards!

**Comment by xiongyan21** [comment]
I am trying using second order FCI and DUCC  to calculate the excitation energies of a small radical.

Very Best Regards!

**Comment by npbauman** [comment]
The quantum features are routines for printing out one- and two-electron integrals that can be utilized in quantum algorithms. The outputs can be interpreted and formatted in YAML files that include the integrals and basic information including initial wavefunction guesses for quantum algorithms. 

There is no quantum algorithm performed by NWChem. In either of the printing options (standard or DUCC), a corresponding CC calculation is done, usually CCSD. It is a standard CCSD calculation. 

As for the issue you are seeing, the DUCC algorithm is memory intensive. That error is saying that the memory is excited when allocating for one of the arrays in the DUCC algorithm. Eventually, a more memory-savvy algorithm will be implemented, but since quantum algorithms can't handle calculations of more than a couple of orbitals, this issue of memory is rarely encountered when ran correctly.

**Comment by xiongyan21** [comment]
Q# and NWChem and NWChem: past, present, and future tell me many things.
Very Best Regards!
