### ISSUE TITLE
Please bundle ga (include ga source inside of nwchem source)

### ISSUE THREAD

**Issue by marcindulak** [nwchemgit/nwchem#40]
Currently the build process tries to download ga from the internet.
This is not allowed when packaging an RPM.

```
No Global Arrays found: Attempting running ./get-tools
./get-tools-github
downloading ga-5.6.5.tar.gz from https://github.com/GlobalArrays/ga/releases/download/v5.6.5/ga-5.6.5.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: github.com
wget failed for ga-5.6.5.tar.gz
trying git clone
 
Failed to download ga-5.6.5.tar.gz
```

I believe I could use the ga source as an additional source included in the spec file definition, but I need to make sure that nwchem releases always use public releases of ga. In this case bundling of the ga source inside of nwchem is not necessary.

**Comment by edoapra** [comment]
Duplicate of https://github.com/nwchemgit/nwchem/issues/28
Please use the hotfix/release-6-8 branch and  env. variable EXTERNAL_GA_PATH (as describe in issue #28 )
The GA version must be >= 5.6.5

**Comment by marcindulak** [comment]
It's good news ga split, but if I don't find a maintainer of ga in Fedora/EPEL I'll need to retire nwchem RPM https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/KUYUMGYUM73TGXBCSYLBKDPN3IHXLLOW/

**Comment by edoapra** [comment]
@marcindulak I am not sure I am following you. Please correct the statements below

1. You state that "... I need to make sure that nwchem releases always use public releases of ga". NWChem 6.8.1 (aka hotfix/release-6-8) currently makes use of GA version 5.6.5. GA 5.6.5 is available on the GlobalArrays release github page https://github.com/GlobalArrays/ga/releases . The failed NWChem compilation you are reporting seem to have failed because the computer used did not resolve the host namegithub.com (Could not resolve host: github.com)
2. What do you exactly mean by bundle? Please provide suggestions on how the current NWChem way of pulling released tarballs of Global Arrays could be improved to fit your definition of bundling

**Comment by marcindulak** [comment]
The failure to resolve github.com is a Fedora protection against downloading sources from the internet during the RPM build process.
I just seem remembering from the past that nwchem was using custom ga snapshot releases, that did not correspond to official ga releases, or required ga built using special flags. If nwchem continued including such custom sources of ga, then there would be a chance that fedora accepts those ga to become a part of nwchem build source.
I would simply add the required ga as an additional source to the spec file https://src.fedoraproject.org/rpms/nwchem/blob/8493b83f5824b3cab844896239a3d626780a2486/f/nwchem.spec#_42.
This is what I asked for in this issue, since I was not aware that the situation has changed, so I'm closing the issue.

In the current state, where nwchem can use an external ga installation, the only solution to continue providing nwchem RPM in Fedora/EPEL is to find a maintainer of ga RPM.

**Comment by edoapra** [comment]
EXTERNAL_GA_PATH needs to contain the location of the bin directory where ga-config is located as in
${EXTERNAL_GA_PATH}/bin/ga-config
