### ISSUE TITLE
Question: what's the meaning of hfexch for range-seprated functionals?

### ISSUE THREAD

**Issue by tzyii** [nwchemgit/nwchem#44]
I note that hfexch are set to 1.0 for all RSH calculations in wiki. What the meaning of hfexch?

**Comment by jeffhammond** [comment]
`hfexch` is Hartree-Fock exchange ([manual](http://www.nwchem-sw.org/index.php/Release66:Density_Functional_Theory_for_Molecules#Exchange-Correlation_Functionals)).  It's 1.0 for all the RSH functionals because those modulate the exchange coefficient using the `cam` terms ([manual](http://www.nwchem-sw.org/index.php/Release66:Density_Functional_Theory_for_Molecules#Range-Separated_Functionals)).  For example, CAMB3LYP does not use 100% exchange at any range, because `cam 0.33 cam_alpha 0.19 cam_beta 0.46` corresponds to an asymptotic weight of `0.19+0.46=0.65` (i.e. 65%).  To be explicit, the `cam_alpha` term scales the Hartree-Fock exchange, so one should not do so redundantly via `hfexch`.

Note that using 100% HF exchange asymptotically reproduces the true physical behavior (1/r decay, as opposed to exp(-r) decay from XC functionals).  Many but not all RSH functionals use `alpha+beta=1` for this reason.  See e.g. equation 4 of http://www.qtp.ufl.edu/ofdft/research/TheorChemAcc135_120.pdf.  There are other good papers on this topic (e.g. [this one](https://www.tandfonline.com/doi/abs/10.1080/0026897031000094443)) but I don't have access to chemistry journals anymore 😢
