### ISSUE TITLE
nwchem doesn't respect LDFLAGS

### ISSUE THREAD

**Issue by yurivict** [nwchemgit/nwchem#64]
On FreeBSD I have the problem that it doesn't use ```-W,-rpath=/usr/local/lib/gcc7``` from ```LDFLAGS```, and the executable gets linked with the wrong ```libgcc_s.so``` and fails.

Please use ```LDFLAGS```.

Version: ```6.8.1-release-94```

**Comment by jeffhammond** [comment]
As best I can tell, `src/config/makefile.h` overwrites `LDFLAGS` at line 2862:
```
LDFLAGS = $(LDOPTIONS) -L$(LIBDIR) $(LIBPATH)
```
If you use `LDOPTIONS`, that might stick.

However, given the number of issues with FreeBSD, it might be prudent to just create a new `NWCHEM_TARGET` for it, rather than keep hacking on the `LINUX(64)` target(s).

**Comment by edoapra** [comment]
@yurivict I have just pushed a patch for fix. It does not require any command line extra option, just gmake

**Comment by yurivict** [comment]
> However, given the number of issues with FreeBSD

I didn't observe any issues on FreeBSD when I ran it.

> I have just pushed a patch for fix. 
This fixed the problem. Thank you!

**Comment by jeffhammond** [comment]
@yurivict By issues, I was referring to the number of recent tickets related to FreeBSD packaging.  A separate NWCHEM_TARGET would all us to implement more specific options without affecting Linux builds.

**Comment by edoapra** [comment]
@jeffhammond we already have a bit in makefile.h that detects FreeBSD since commit a78a9908159be4b56c9605a6df0feb718d5203b9

https://github.com/nwchemgit/nwchem/commit/a78a9908159be4b56c9605a6df0feb718d5203b9#diff-1750a4dcc9a0a9b1773d275e96c46a1e

GOTFREEBSD= $(shell uname -o 2>&1|awk ' /FreeBSD/ {print "1";exit}')

Let's avoid newer targets, if possible, since it makes maintenance more complex (e.g. Macs)

**Comment by jeffhammond** [comment]
@edoapra Eventually, I'd like to split the compiler and OS aspects of the build system so this is all a lot simpler to manage.  I'll try to work on it in 2019.
