### ISSUE TITLE
NWChem did not use the GPU during testing.

### ISSUE THREAD

**Issue by Schroedingers0216** [nwchemgit/nwchem#999]
I compiled the HIP version of NWChem, but when I tested it, I found that the GPU was not involved in the computation and that the CPU was primarily used. I believe my compilation was correct, so why is the GPU not being utilized?

compiler:
export ROCM_PATH=/usr/local/rocm/
export NWCHEM_TOP=/opt/nwchem
export NWCHEM_TARGET=LINUX64
export ARMCI_NETWORK=MPI-PR
export MKLROOT=/public/intel-compiler/2021.3.0/mkl
export USE_MPI=yes
export USE_MPIF=yes
export USE_MPIF4=yes
export TCE_HIP=yes
export NWCHEM_MODULES=all
export BLASOPT="-L${MKLROOT}/lib/intel64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5 -lpthread -lm -ldl 
export USE_64TO32=y
export BLAS_SIZE=4
export LD_LIBRARY_PATH=${ROCM_PATH}/hip/lib:$LD_LIBRARY_PATH

make nwchem_config
make 64_to_32
make -j128

test:
mpirun -np 4 /opt/nwchem/bin/LINUX64/nwchem 3carbo_dft.nw 
Total times  cpu:      696.0s     wall:      727.8s

**Comment by jeffhammond** [comment]
`./github/examples/qmd/3carbo_dft.nw` uses the DFT module, which has no GPU support as far as I know.  Even if it did, dynamics with 3-21G would not run efficiently without a totally rewritten GPU implementation of DFT.

The GPU support in NWChem is limited to CCSD(T).  I recall the HIP support is specific to TCE CCSD(T).  @mjklemm knows more.

I am closing this because it's not an issue in NWChem.  There is https://github.com/nwchemgit/nwchem/discussions and the user list for discussion.
